name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build test_runner
      id: build-test_runner
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build test_runner
        setup-command: ''
        command: make
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD-TEST_RUNNER_RESULTS: "${{steps.build-test_runner.outputs.result}}"
      with:
        runners: build-test_runner
