name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build test
      id: build-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build test
        setup-command: ''
        command: gcc -c cunit-src/*.c -I include && ar rcs lib/libCUnit.a *.o && gcc
          -o test_runner test/test_tinh_tong.c src/my_functions.c -I include -Llib
          -lCUnit
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUILD-TEST_RESULTS: "${{steps.build-test.outputs.result}}"
      with:
        runners: build-test
